# Generated by Django 3.2.3 on 2021-05-26 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_todo_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='details',
        ),
    ]
